version: "3.9"

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: webapp:latest
    network_mode: host
    ports:
      - "3000:3000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
