apiVersion: v1
kind: Service
metadata:
  name: example-webapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: example-webapp
---
apiVersion: v1
kind: Pod
metadata:
  name: example-webapp
  labels:
    app: example-webapp
spec:
  restartPolicy: Never

  containers:

  - name: webapp
    image: test
    imagePullPolicy: Never
    ports:
      - containerPort: 3000

  - name: redis
    image: redis
    ports:
      - containerPort: 6379
